### ISSUE TITLE
Send kafka matrices to Prometheus

### ISSUE THREAD

**Issue by taherbohari** [cloudflare/kafka_zookeeper_exporter#7]
Hello all,

I have built the Kafka exporter using the steps mentioned in READ ME. I can see the matrices when I fire the curl command as per the instructions. But I want to pass these matrices to my Prometheus machine and Prometheus pulls the matrices from "localhost:9381/metrics". How can I get the metrics on this web address? Or is there any other way I can pass on this Kafka metrics to my Prometheus.

**Comment by prymitive** [comment]
See https://github.com/cloudflare/kafka_zookeeper_exporter/pull/8, I've added an example there
